###
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "username": "Souli",
  "password": "Souli"
}

###
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "username": "Souli",
  "password": "Souli"
}

###
GET {{baseUrl}}/auths/users